version: '3.7'

services:
  django:
    platform: linux/amd64
    build: .
    container_name: tc-web-django-dev-container
    image: tc-web-django-dev-image
    ports:
      - 8007:8007
    depends_on:
      - postgres
    volumes:
      - .:/code
      - ../tc-web-volumes/static:/tc-web-volumes/static
      - ../tc-web-volumes/media:/tc-web-volumes/media
      - ../tc-web-volumes/bucket:/bucket
    command: /srv/start
    restart: always
    env_file:
      - .env
  postgres:
    platform: linux/amd64
    build: ./postgres/
    image: tc-web-psql-dev-image
    shm_size: '1g'
    container_name: tc-web-postgres-container
    restart: always
    volumes:
      - ../tc-web-volumes/pgdata:/var/lib/postgresql/data/pgdata
      - ../tc-web-volumes/bucket:/bucket
      # - ../tc-web-volumes/media/archive:/archive
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
     - .env
  mysql:
    platform: linux/amd64
    build: ./scripts/mysql
    container_name: tc-web-mysql-container
    ports:
      - "3307:3306"
    image: tc-web-mysql-image
    restart: always
    # environment:
    #   MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    # env_file:
      # - ./app/.env
    volumes:
      - ../tc-web-volumes/mysql:/var/lib/mysql:rw
      - ../tc-web-volumes/bucket:/bucket
      # - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:rw
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
  solr:
    build: ./solr-workspace
    image: taicol-solr-image
    container_name: taicol-solr-container
    ports:
      - "8983:8983"
    restart: always
    volumes:
      - ../tc-web-volumes/solr:/var/solr
      - ../tc-web-volumes/bucket:/bucket
      - ./solr-workspace/:/workspace
    # command:
      # - solr-precreate
      # - tbia_records
    environment:
      - SOLR_JAVA_MEM=-Xms4g -Xmx4g