networks:
  gateway:
    external: true
  traefik-web:
    external: true

services:
  django:
    build: .
    container_name: tc-web-django-stag-container
    image: tc-web-django-stag-image
    expose:
      - 8001
    depends_on:
      - postgres
      - mysql-web
    volumes:
      - .:/code
      - ../tc-web-volumes/static:/tc-web-volumes/static
      - ../tc-web-volumes/media:/tc-web-volumes/media
      - ../tc-web-volumes/bucket:/bucket
    command: /srv/start
    restart: always
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - gateway
      - traefik-web
  postgres:
    image: postgres:14-alpine
    shm_size: '1g'
    container_name: tc-stag-postgres-container
    restart: always
    volumes:
      - ../tc-web-volumes/pgdata:/var/lib/postgresql/data/pgdata
      - ../tc-web-volumes/bucket:/bucket
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
     - .env
    networks:
      - gateway
  mysql-web:
    build: ./scripts/mysql
    container_name: tc-web-mysql-container
    ports:
      - "3307:3306"
    image: tc-web-mysql-image
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ../tc-web-volumes/mysql:/var/lib/mysql:rw
      - ../tc-web-volumes/bucket:/bucket
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    networks:
      - gateway
  solr:
    build: ./solr-workspace
    image: taicol-solr-image
    container_name: taicol-solr-container
    ports:
      - "8983:8983"
    restart: always
    volumes:
      - ../tc-web-volumes/solr:/var/solr
      - ../tc-web-volumes/bucket:/bucket
      - ./solr-workspace/:/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - gateway
  nginx-web:
    image: nginx:1.19.10-alpine
    container_name: nginx-web
    restart: always
    volumes:
      - ./scripts/nginx/staging:/etc/nginx/conf.d
      - ../tc-web-volumes/static:/tc-web-volumes/static
      - ../tc-web-volumes/media:/tc-web-volumes/media
      - ../tc-web-volumes/logs/nginx:/var/log/nginx
    networks:
      - traefik-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-web.rule=Host(`web-staging.taicol.tw`)"
      - "traefik.http.routers.nginx-web.entrypoints=websecure"
      - "traefik.http.routers.nginx-web.tls.certresolver=myresolver"
