version: '3.7'

services:
  django:
    build: .
    container_name: tc-web-django-stag-container
    image: tc-web-django-stag-image
    ports:
      - 8001:8001
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/code
      - ../tc-web-volumes/static:/tc-web-volumes/static
      - ../tc-web-volumes/media:/tc-web-volumes/media
      - ../tc-web-volumes/bucket:/bucket
    command: /srv/start
    restart: always
    env_file:
      - .env
  postgres:
    image: postgres:14-alpine
    shm_size: '1g'
    container_name: tc-stag-postgres-container
    restart: always
    volumes:
      - ../tc-web-volumes/pgdata:/var/lib/postgresql/data/pgdata
      - ../tc-web-volumes/bucket:/bucket
      - ../tc-web-volumes/media/archive:/archive
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
     - .env
  # nginx:
  #   image: nginx:1.19.10-alpine
  #   restart: always
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./scripts/nginx/staging:/etc/nginx/conf.d
  #     - ../tc-web-volumes/static:/tc-web-volumes/static
  #     - ../tc-web-volumes/media:/tc-web-volumes/media
  #     - ../tc-web-volumes/logs/nginx:/var/log/nginx
  #   links:
  #     - django:django
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "1m"
  #       max-file: "3"
