networks:
  gateway:
    external: true
  traefik-admin:
    external: true

services:
  react_app:
    depends_on:
      - mysql
    container_name: taicol-react-app
    restart: always
    expose:
      - 3000
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./app/node_modules:/app/node_modules
      - ./app/.next:/app/.next
      - ./app/public/upload:/app/public/upload
    env_file:
      - ./app/.env
    networks:
      - gateway
      - traefik-admin
  nginx-admin:
    container_name: nginx-admin
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/public/upload:/upload
    networks:
      - traefik-admin
  mysql:
    container_name: taicol-react-mysql
    ports:
      - 3306:3306
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    env_file:
      - ./app/.env
    volumes:
      - ./db:/var/lib/mysql:rw
      - ../../tc-web-volumes/bucket:/bucket
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    networks:
      - gateway
