# Generated by Django 5.2.16 on 2026-07-15 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Download',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
