stag-up:
	docker compose -f staging.yml up -d

stag-down:
	docker compose -f staging.yml down

stag-logs:
	docker compose -f staging.yml logs -f

prod-up:
	docker compose -f production.yml up -d

prod-down:
	docker compose -f production.yml down

prod-logs:
	docker compose -f production.yml logs -f