networks:
  traefik-admin:
    external: true
  traefik-web:
    external: true
  traefik-api:
    external: true

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=catalogueoflife.taiwan@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik-admin
      - traefik-web
      - traefik-api