#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ "$WEB_ENV" == "prod" ] || [ "$WEB_ENV" == "staging" ]; then
    python manage.py migrate --no-input
    python manage.py collectstatic --no-input
    gunicorn --bind 0.0.0.0:8001 \
    --workers 4 \
    --threads 2 \
    --timeout 60 \
    conf.wsgi
else
    python manage.py migrate
    python manage.py collectstatic --no-input
    python manage.py runserver 0.0.0.0:8007
fi
