# Generated by Django 4.0.6 on 2022-07-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0002_expert_name_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
