# Generated by Django 4.0.6 on 2022-07-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0003_alter_expert_created_at_alter_expert_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon_id', models.CharField(max_length=7)),
                ('count', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
