# Generated by Django 4.0.6 on 2022-08-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
