# Generated by Django 4.1 on 2023-03-02 14:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0006_alter_feedback_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='taxon_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='錯誤描述'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_solved',
            field=models.BooleanField(default=False, verbose_name='已解決'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='notify',
            field=models.BooleanField(default=True, verbose_name='更新通知與否'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='回覆模板'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='taxon_id',
            field=models.CharField(max_length=7, verbose_name='物種編號'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='主旨'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '學名和中文名'), (2, '照片'), (3, '分類資訊'), (4, '分類階層'), (5, '物種資訊'), (6, '學名變遷'), (7, '文獻'), (8, '專家'), (9, '相關連結'), (10, '變更歷史'), (11, '有效名版本紀錄')], null=True, verbose_name='類型'),
        ),
        migrations.AlterField(
            model_name='searchstat',
            name='taxon_id',
            field=models.CharField(max_length=8),
        ),
    ]
