# Generated by Django 4.1 on 2023-03-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0007_alter_expert_taxon_id_alter_feedback_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='taxon_id',
            field=models.CharField(max_length=8, verbose_name='物種編號'),
        ),
    ]
