# Generated by Django 4.1 on 2023-05-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0008_alter_feedback_taxon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reference',
            field=models.TextField(blank=True, null=True, verbose_name='來源文獻/參考資料'),
        ),
    ]
