# Generated by Django 5.2.16 on 2026-07-15 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0009_feedback_reference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='expert',
        ),
    ]
