# Generated by Django 5.2.16 on 2026-07-15 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxa', '0010_delete_expert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
